### ISSUE TITLE
Missing GitHub repository

### ISSUE THREAD

**Issue by infracritical** [webrecorder/webrecorder-setup#3]
Seems that the **https://github.com/JeroenED/ansible-role-certbot.git** file is missing as the repository "https://github.com/JeroenED/ansible-role-certbot.git" is missing.

If you're going to offer this version of the product, you might want to keeping it up-to-date; unless of course, you're moving away from this product, of which you may want to simply archive it and state so.

**Comment by dwaaan** [comment]
Open requirements.yml, 

`#- src: geerlingguy.certbot`
`- src: git+https://github.com/JeroenED/ansible-role-certbot.git`

Uncomment the first line and comment the second line.

**Comment by dwaaan** [comment]
also do the same in `/roles/certbot/tasks/main.yml`
